rules:
  - id: zsh-kit.comment.todo
    languages: [generic]
    message: TODO marker (unfinished work or missing edge cases).
    severity: INFO
    pattern-regex: "\\bTODO\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.comment.fixme
    languages: [generic]
    message: FIXME marker (known-bad behavior).
    severity: WARNING
    pattern-regex: "\\bFIXME\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.comment.bug
    languages: [generic]
    message: BUG marker (explicit bug note).
    severity: WARNING
    pattern-regex: "\\bBUG\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.comment.hack
    languages: [generic]
    message: HACK marker (workaround or suspicious code).
    severity: WARNING
    pattern-regex: "\\bHACK\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.comment.xxx
    languages: [generic]
    message: XXX marker (placeholder or code smell).
    severity: INFO
    pattern-regex: "\\bXXX\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.shell.typeset-empty-string-double-quotes
    languages: [generic]
    message: Prefer ='' over ="" in typeset/local lines.
    severity: INFO
    pattern-regex: '^[ \t]*(?:typeset|local)\b.*=""'
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.shell.eval
    languages: [generic]
    message: Avoid eval in shell scripts; prefer arrays or explicit parsing.
    severity: WARNING
    pattern-regex: "^[ \\t]*eval\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

  - id: zsh-kit.shell.curl-pipe-shell
    languages: [generic]
    message: Avoid piping curl/wget output to a shell (supply-chain risk).
    severity: ERROR
    pattern-regex: "^[ \\t]*(?:curl|wget)\\b[^|]*\\|[ \\t]*(?:sh|bash|zsh)\\b"
    paths:
      include:
        - "*.sh"
        - "*.zsh"
        - ".zshenv"
        - ".zprofile"
        - ".zshrc"

