#!/usr/bin/env -S zsh -f

setopt no_nomatch

source "$ZDOTDIR/scripts/git/git-lock.zsh"

if ! typeset -f git-lock >/dev/null; then
  printf "❗ 'git-lock' is not defined as a function.\n"
  exit 1
fi

git-lock "$@" || exit $?
