#!/usr/bin/env zsh

setopt no_nomatch

source "$ZDOTDIR/scripts/git/git-lock.sh"

if ! typeset -f git-lock >/dev/null; then
  printf "❗ 'git-lock' is not defined as a function.\n"
  exit 1
fi

git-lock "$@" || exit $?