#!/usr/bin/env zsh

setopt no_nomatch

source "$ZDOTDIR/scripts/git/git-summary.sh"

if ! typeset -f git-summary >/dev/null; then
  printf "❗ 'git-summary' is not defined as a function.\n"
  exit 1
fi

git-summary "$@" || exit $?