#!/usr/bin/env zsh

setopt no_nomatch

source "$ZDOTDIR/scripts/git/git-scope.sh"

if ! typeset -f git-scope >/dev/null; then
  echo "❗ 'git-scope' is not defined as a function."
  exit 1
fi

git-scope "$@" || exit $?